ignored_paths:
  - extension/observer
  - extension/encoding
  - extension/opampcustommessages
  - processor/tailsamplingprocessor
allowed_functions:
  - name: NewFactory
    parameters:
    return_types: [connector.Factory]
  - name: NewFactory
    parameters:
    return_types: [exporter.Factory]
  - name: NewFactory
    parameters:
    return_types: [extension.Factory]
  - name: NewFactory
    parameters:
    return_types: [processor.Factory]
  - name: NewFactory
    parameters:
    return_types: [receiver.Factory]

ignored_functions:
  - ^Test.*
  - ^Benchmark.*
  - ^Fuzz.*
