receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8890']
            - targets: ['localhost:8889']
            - targets: ['localhost:8888']

exporters:
  splunk:
    # Splunk HTTP Event Collector token
    token: "00000000-0000-0000-0000-0000000000000"
    # URL to a Splunk instance to send data to.
    url: "https://splunk:8088/services/collector"
    # Optional Splunk source: https://docs.splunk.com/Splexicon:Source
    source: "otel"
    # Optional Splunk source type: https://docs.splunk.com/Splexicon:Sourcetype
    sourceType: "otel"
    # Splunk index, optional name of the Splunk index targeted
    index: "metrics"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [splunk]
