# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: jmxreceiver

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Add `temp_dir` configuration key to JMX receiver

# One or more tracking issues related to the change
issues: [14757]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: Adds an optional configuration property allowing the user to decide where to place the temporary properties file used by the JMX receiver Java process.
